const fs = require('fs');
const path = require('path');

// Zero-dependency helper to read .env file for local development
function loadEnv(envPath) {
    if (!fs.existsSync(envPath)) return {};
    const content = fs.readFileSync(envPath, 'utf8');
    const env = {};
    content.split('\n').forEach(line => {
        const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
        if (match) {
            const key = match[1];
            let value = match[2] || '';
            // Remove quotes if they exist
            if (value.length > 0 && value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
            if (value.length > 0 && value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1);
            env[key] = value;
        }
    });
    return env;
}

const localEnv = loadEnv(path.resolve(__dirname, '../.env'));

const config = {
    ADMIN_EMAIL: process.env.ADMIN_EMAIL || localEnv.ADMIN_EMAIL || 'admin@example.com',
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || localEnv.ADMIN_PASSWORD || 'password',
    BREVO_API_KEY: process.env.BREVO_API_KEY || localEnv.BREVO_API_KEY || 'YOUR_BREVO_API_KEY_HERE',
    BREVO_API_URL: process.env.BREVO_API_URL || localEnv.BREVO_API_URL || 'https://api.brevo.com/v3/smtp/email',
    SENDER_EMAIL: process.env.SENDER_EMAIL || localEnv.SENDER_EMAIL || 'sender@example.com',
    SENDER_NAME: process.env.SENDER_NAME || localEnv.SENDER_NAME || 'School IT Department',
    SCHOOL_NAME: process.env.SCHOOL_NAME || localEnv.SCHOOL_NAME || 'School Name',
    SCHOOL_ADDRESS: process.env.SCHOOL_ADDRESS || localEnv.SCHOOL_ADDRESS || 'School Address',
    SCHOOL_PHONE: process.env.SCHOOL_PHONE || localEnv.SCHOOL_PHONE || 'School Phone'
};

const content = `// System Configuration - AUTO-GENERATED BY BUILD SCRIPT
const CONFIG = ${JSON.stringify(config, null, 4)};
`;

const configPath = path.resolve(__dirname, '../js/config.js');
// Ensure the directory exists
const dir = path.dirname(configPath);
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(configPath, content);
console.log('js/config.js generated successfully!');
