const fs = require('fs');
const path = require('path');

// Read from process.env or fallback to .env file for local dev
try {
    require('dotenv').config({ path: path.resolve(__dirname, '../.env') });
} catch (e) {
    // If dotenv is not found, just skip it. Vercel will have variables in process.env
}

const config = {
    ADMIN_EMAIL: process.env.ADMIN_EMAIL || 'admin@example.com',
    ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || 'password',
    BREVO_API_KEY: process.env.BREVO_API_KEY || 'YOUR_BREVO_API_KEY_HERE',
    BREVO_API_URL: process.env.BREVO_API_URL || 'https://api.brevo.com/v3/smtp/email',
    SENDER_EMAIL: process.env.SENDER_EMAIL || 'sender@example.com',
    SENDER_NAME: process.env.SENDER_NAME || 'School IT Department',
    SCHOOL_NAME: process.env.SCHOOL_NAME || 'School Name',
    SCHOOL_ADDRESS: process.env.SCHOOL_ADDRESS || 'School Address',
    SCHOOL_PHONE: process.env.SCHOOL_PHONE || 'School Phone'
};

const content = `// System Configuration - AUTO-GENERATED BY VERCEL BUILD
const CONFIG = ${JSON.stringify(config, null, 4)};
`;

fs.writeFileSync(path.resolve(__dirname, '../js/config.js'), content);
console.log('js/config.js generated successfully!');
